"""add users table

Revision ID: 3296763c9cec
Revises: 89207aa44d23
Create Date: 2025-01-15 22:13:46.684273

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3296763c9cec"
down_revision: Union[str, None] = "89207aa44d23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("first_name", sa.String(length=75), nullable=False),
        sa.Column("last_name", sa.String(length=75), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=False),
        sa.Column("mobile_no", sa.String(length=15), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("otp", sa.String(length=4), nullable=True),
        sa.Column("otp_secret_key", sa.String(length=32), nullable=True),
        sa.Column("is_otp_verified", sa.Boolean(), nullable=True),
        sa.Column("otp_count", sa.Integer(), nullable=True),
        sa.Column("resent_otp_count", sa.Integer(), nullable=True),
        sa.Column("last_otp_sent_at", sa.DateTime(), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(), nullable=True),
        sa.Column("is_reset_resent_otp_count", sa.Boolean(), nullable=True),
        sa.Column("encrypted_password", sa.Text(), nullable=True),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("sign_in_count", sa.Integer(), nullable=True),
        sa.Column("current_sign_in_ip", sa.String(length=50), nullable=True),
        sa.Column("last_sign_in_ip", sa.String(length=50), nullable=True),
        sa.Column("current_sign_in_at", sa.DateTime(), nullable=True),
        sa.Column("last_sign_in_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
